from workflow.workflow import Workflow

WF = Workflow()
WF.rerun_failed_calculations()
